apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: __NFS_SERVER_IP_OR_HOSTNAME__
    path: __YOUR_NFS_PATH__
    readOnly: false

---
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  labels:
    app: oracledb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcldb
  labels:
    app: oracledb
spec:
  selector:
    matchLabels:
      app: oracledb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracledb
    spec:
      containers:
      - image: oracle/database:19.3.0-ee
        name: orcldb
        env :
        - name : ORACLE_SID
          value : __CHANGEME__
        - name : ORACLE_PDB
          value : __CHANGEME__        
        - name : ORACLE_PWD
          value : __CHANGEME__
        - name : ORACLE_CHARACTERSET
          value : AL32UTF8
        ports:
        - containerPort: 1521
          name: orcldb
        - containerPort: 5500
          name: em
        volumeMounts:
        - name: data
          mountPath: /opt/oracle/oradata
      securityContext:
        runAsNonRoot: true
        runAsUser: 54321
        fsGroup: 54321
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-pvc

---
apiVersion: v1
kind: Service
metadata:
 name: oracledb
spec:
 type: LoadBalancer
 selector:
   app: oracledb
 ports:
   - name: client
     protocol: TCP
     port: 1521
     nodePort: 31521
   - name: em
     protocol: TCP
     port: 5500
     nodePort: 31525
 selector:
   app: oracledb
