apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pvc
  labels:
    app: oracledb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: rook-ceph-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcldb
  labels:
    app: oracledb
spec:
  selector:
    matchLabels:
      app: oracledb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracledb
    spec:
      containers:
      - image: invaleed/oracledb:19.3.0-ee
        name: orcldb
        env :
        - name : ORACLE_SID
          value : __CHANGEME__ 
        - name : ORACLE_PDB
          value : __CHANGEME__        
        - name : ORACLE_PWD
          value : __CHANGEME__
        - name : ORACLE_CHARACTERSET
          value : AL32UTF8
        ports:
        - containerPort: 1521
          name: orcldb
        volumeMounts:
        - name: data
          mountPath: /opt/oracle/oradata
      securityContext:
        runAsNonRoot: true
        runAsUser: 54321
        fsGroup: 54321
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oracle-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: oracledb
spec:
 type: LoadBalancer
 selector:
   app: oracledb
 ports:
   - name: client
     protocol: TCP
     port: 1521
     nodePort: 31521
 selector:
   app: oracledb
